variables:
  change:
    popo: is changing by key
check:
  continue: false

security:
  auth: none

test:
  properties:
    popo: replacing key variables.change.popo by ${variables.change.popo} with ENV ${USERPROFILE}
