name: Deploy
on:
  workflow_dispatch:
    inputs:
      modules:
        description: modules do you want build separate by space
        required: false
        default: ''
      env:
        description: environment to build
        required: false
        type: choice
        options:
          - dev
          - prod
        default: 'dev'
  pull_request_target:
    types:
      - closed
    branches:
      - develop
      - main

permissions: write-all

jobs:
  context:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: metadata
        id: metadata
        uses: pmeig/github-actions/actions/context/metadata@main
      - name: find last release
        id: release
        if: ${{ steps.metadata.outputs.env-target == 'prod' && github.event_name != 'workflow_dispatch' }}
        uses: pmeig/github-actions/actions/github/release/latest@main
      - name: retrieve module change
        id: modules-accepted
        if: ${{ steps.metadata.outputs.env-target == 'prod' && github.event_name != 'workflow_dispatch' }}
        uses: pmeig/github-actions/actions/github/diff@main
        with:
          target: ${{ steps.release.outputs.target }}
          origin: ${{ steps.metadata.outputs.tag }}
          includes: 'start=modules'
      - name: prepare modules
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.modules != '' }}
        id: files
        run: |  
          files=''
          for file in ${{ inputs.modules }}
          do
            files="$files modules/$file"
          done
          echo "value=${files:1}" >> $GITHUB_OUTPUT
      - name: suffix version
        id: suffix
        uses: pmeig/github-actions/actions/context/version/suffix@main
        with:
          env: ${{ steps.metadata.outputs.env-target }}
      - name: find modules
        id: modules
        run: |
          json=$(jq -rc '.projects | to_entries | map( {"name": .key, "root": ("./" + .value.location.root)})' pmeig-cli.json)
          filter='${{ steps.files.outputs.value }}${{ steps.modules-accepted.outputs.files }}'
          if [ -n "$filter" ]
          then
            selection='[]'
            modules=''
            for file in $filter
            do
              select=$(echo $json | jq -rc --arg root "./$file" '. | map(select(.root as $compare | $root | startswith($compare))) | .[]')
              module=$(echo $select | jq -rc '.name')
              if [[ " $modules " != *" $module "* ]]
              then
                version=$(jq -rc '.version' $(echo $select | jq -rc '.root')/package.json | cut -d'-' -f1)
                selection=$( echo $selection | jq -rc --argjson select "$select" \
                  --arg version "$version${{ steps.suffix.outputs.value }}" \
                  '. += [$select + {"version": $version}]')
                modules="$modules $module"
              fi
            done
            json="$selection"
          fi
          echo "value=$json" >> $GITHUB_OUTPUT
      - name: env accepted
        id: env
        run: |
          env='${{ steps.metadata.outputs.env-target }}'
          if [ '${{ github.event_name }}' == 'workflow_dispatch' ]
          then
            env='dev'
          fi
          echo "value=$env" >> $GITHUB_OUTPUT
    outputs:
      env: ${{ steps.env.outputs.value }}
      modules: ${{ steps.modules.outputs.value }}
      artifactory: ${{ steps.metadata.outputs.npm-target }}
      target: ${{ steps.metadata.outputs.target }}
  build:
    needs: context
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    environment: ${{ needs.context.outputs.env }}
    env:
      PMEIG_TOKEN: ${{ secrets.PMEIG_TOKEN }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.context.outputs.modules) }}
      max-parallel: 3
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: load secrets
        uses: pmeig/github-actions/actions/secret/vault@main
        id: vault
        with:
          cache: 'false'
          role-id: ${{ secrets.VAULT_ROLE_ID }}
          secret-id: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            pmeig/server/data/cicd/jfrog/writer user | ARTIFACTORY_USER;
            pmeig/server/data/cicd/jfrog/writer password | ARTIFACTORY_PASSWORD;
            pmeig/server/data/cicd/npm user | REMOTE_USER;
            pmeig/server/data/cicd/npm token | REMOTE_TOKEN;
      - name: node setup
        uses: pmeig/github-actions/actions/node/setup@main
        id: node-setup
        with:
          remote-token: ${{ env.REMOTE_TOKEN }}
          artifactory-password: ${{ env.ARTIFACTORY_PASSWORD }}
          artifactory-user: ${{ env.ARTIFACTORY_USER }}
          branch: ${{ needs.context.outputs.target }}
      - name: install dependencies
        id: projects
        run: |
          json='{}'
          for package in $(find . -name 'package.json')
          do
            dir=$(dirname $package)
            name=$(jq -rc '.name' $package)
            json=$(echo $json | jq -rc --arg name "$name" --arg dir "$dir" '. + {($name): $dir}')
          done
          echo "value=$json" >> $GITHUB_OUTPUT
          pnpm install
      - name: actualize version
        working-directory: ${{ matrix.module.root }}
        run: |
          pnpm version ${{ matrix.module.version}}
      - name: install cli
        id: cli
        run: |
          pnpm build:cli
          cp modules/cli/package.json dist/cli/package.json
          cp modules/cli/README.md dist/cli/README.md
          cd dist/cli
          pnpm pack
          mv *.tgz cli.tgz
          cd ../..
          pnpm -w install dist/cli/cli.tgz
          if [ '${{ matrix.module.name }}' = 'cli' ]
          then
            echo 'path=dist/cli/cli.tgz' >> $GITHUB_OUTPUT
          fi
      - name: build module
        if: ${{ matrix.module.name != 'cli' }}
        working-directory: ${{ matrix.module.root }}
        run: |
          cat ../../dist/cli/package.json
          echo my package.json
          cat package.json
          pnpm build
      - name: pack
        id: pack
        if: ${{ matrix.module.name != 'cli' }}
        working-directory: dist/${{ matrix.module.name }}
        run: |
          pnpm pack
          mv *.tgz ${{ matrix.module.name }}.tgz
          echo "path=dist/${{ matrix.module.name }}/${{ matrix.module.name }}.tgz" >> $GITHUB_OUTPUT
      - name: deploy on remote
        run: |
          options='--no-git-checks'
          if [ '${{ needs.context.outputs.env }}' != 'prod' ]
          then
            options="$options --tag snapshot"
          fi
          # pnpm publish ${{ steps.pack.outputs.path }}${{ steps.cli.outputs.path }} $options
          pnpm config delete @pmeig:registry
          pnpm publish ${{ steps.pack.outputs.path }}${{ steps.cli.outputs.path }} --access public $options
  prepare-tag:
    if: ${{ needs.context.outputs.env == 'prod' }}
    needs:
      - build
      - context
    uses: ./.github/workflows/version.yml
    with:
      modules: ${{ needs.context.outputs.modules }}
  tag:
    needs:
      - prepare-tag
      - context
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    strategy:
      max-parallel: 3
      matrix:
        module: ${{ fromJSON(needs.context.outputs.modules) }}
    steps:
      - name: create tag
        uses: pmeig/github-actions/actions/github/release@main
        with:
          name: ${{ matrix.module.name }}_${{ matrix.module.version }}
          tag_name: ${{ matrix.module.name }}_${{ matrix.module.version }}
          branch: main
  tag-date:
    needs: tag
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: tag
        id: tag
        run: |
          current=$(date +YYYY_MM_JJ)
          echo "value=release_$current" >> $GITHUB_OUTPUT
      - name: create tag
        uses: pmeig/github-actions/actions/github/release@main
        with:
          name: ${{ steps.tag.outputs.value }}
          tag_name: ${{ steps.tag.outputs.value }}
          branch: main


  next-feature:
    needs:
      - build
      - context
    if: ${{ needs.context.outputs.env == 'prod' }}
    environment: manual
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: checkout project
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: push next feature
        id: staging
        run: |
          staging=''
          modules=''
          for module in $(echo '${{ needs.context.outputs.modules }}' | jq -rc '.[]')
          do
            path=$(echo $module | jq -rc '.root')
            package="$path/package.json"
            release=$(echo $module | jq -r '.version' | cut -d'.' -f2)
            version=$(jq -r '.version' $package)
            version=$(echo "$version" | cut -d'-' -f1)
            major=$(echo "$version" | cut -d'.' -f1)
            minor=$(echo "$version" | cut -d'.' -f2)
            
            if (( $minor == $release ))
            then
              jq --arg version "$major.$((minor + 1)).0-SNAPSHOT" '.version = $version' $package > $package
              modules="$modules $(echo $module | jq -rc 'name')"
              staging="$staging $package"
            fi
          done
          
          echo "modules=$modules" >> $GITHUB_OUTPUT
          echo "value=$staging" >> $GITHUB_OUTPUT
      - name: commit next feature
        if: ${{ steps.staging.outputs.value != '' }}
        uses: pmeig/github-actions/actions/github/push@main
        with:
          commit: "semver(minor): bump next feature for${{ steps.staging.outputs.modules }}"
          stage: ${{ steps.staging.outputs.value }}
          mail: 'pierrick.workplace@gmail.com'
          user: 'pmeig'
