name: Breaking-change
on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
        description: 'contains list of modules json like this [{ "name": "vault", "root": "./modules/vault", "version": "1.0.0-SNAPSHOT" }]'
  workflow_dispatch:
    inputs:
      modules:
        type: string
        required: true
        description: all modules separate by space

permissions:
  id-token: write
  deployments: write
  contents: write

jobs:
  bump:
    runs-on:
      - self-hosted
      - Linux
      - pmeig
    steps:
      - name: checkout project
        uses: actions/checkout@v4
      - name: get branch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: branch
        uses: pmeig/github-actions/actions/github/branch@main
      - name: env
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: env
        uses: pmeig/github-actions/actions/context/env@main
        with:
          branch: ${{ steps.branch.outputs.target }}
      - name: to json
        if: ${{ github.event_name == 'workflow_dispatch' && steps.env.outputs.value == 'dev' }}
        id: modules
        run: |
          json=$(jq -rc '.projects | to_entries | map( {"name": .key, "root": ("./" + .value.location.root)})' pmeig-cli.json)
          modules='[]'
          compare='${{ inputs.modules }}'
          if [ -z "$compare" ]
          then
            compare=$(echo $json | jq -c '.[] | .name')
          fi
          for root in $(echo "$json" | jq -rc '.[]')
          do
            name=$(echo $root | jq -rc '.name')
            if [[ " $compare " == *" $name "* ]]
            then
              path=$(echo $root | jq -rc '.root')
              version=$(jq -rc '.version' $path/package.json)
              major=$(echo $version | cut -d'.' -f1)
              version="$(( major + 1 )).0.0-SNAPSHOT"
              modules=$(echo $modules | jq -rc --argjson json "$root" \
              --arg version "$version" \
              '. += [$json + {"version": $version}]'])
            fi
          done
          echo "value=$modules" >> $GITHUB_OUTPUT
          echo "context=$json" >> $GITHUB_OUTPUT
      - name: context dependencies
        id: context
        run: |
          json='${{ steps.modules.outputs.context }}'
          modules='${{ steps.modules.outputs.value }}'
          value='[]'
          for module in $modules
          do
            path=$(echo $module | jq -rc '.root')
            name=$(jq -rc '.name' $path/package.json)
            for other in $(echo $json | jq -c --argjson current "$module" '.[] | select(.name as $name | $current.name != $name)')
            do
              root=$(echo $other | jq -rc '.root')
              dependencies=$(jq -rc --argjson current "$name" '.dependencies | keys | map(select(. as $name | $current == $name)) | .[]' $root/package.json)
              if [ -n "$dependencies" ]
              then
                module=$(echo $module | jq -rc --argjson other "$other" '.dependencies += [$other.root + "/package.json"]')
              fi
              dependencies=$(jq -rc --argjson current "$name" '.devDependencies | keys | map(select(. as $name | $current == $name)) | .[]' $root/package.json)
              if [ -n "$dependencies" ]
              then
                module=$(echo $module | jq -rc --argjson other "$other" '.devDependencies += [$other.root + "/package.json"]')
              fi
            done
            value=$(echo $value | jq -rc --argjson module "$module" '. += [$module]')
          done
          echo "value=$value" >> $GITHUB_OUTPUT
      - name: semver type
        id: type
        run: |
          if [ '${{ github.event_name }}' == 'workflow_dispatch' ]
          then
            type='major'
          else
            type='minor'
          fi
          echo "value=$type" >> $GITHUB_OUTPUT
      - name: bump version
        if: ${{ github.event_name == 'workflow_call' || steps.env.outputs.value == 'dev' }}
        id: staging
        run: |
          staging=''
          modules='${{ steps.context.outputs.value }}'
          names=''
          for context in $(echo $modules | jq -c '.[]')
          do
            path=$(echo $context | jq -r '.root')
            package="$path/package.json"
            name=$(jq -rc '.name' $package)
            version=$(echo $context | jq -rc '.version')
            json=$(jq --arg version "$version" '. += {"version": $version}' $package)
            staging="$staging $package"
            names="$names $(echo $context | jq -rc '.name')"
            for dependency in $(echo $context | jq -rc '.dependencies | .[]')
            do
              json=$(echo $json | jq --arg version "$version" --arg name "$name" '.dependencies += {($name): "^" + $version}')
            done
            for dependency in $(echo $context | jq -rc '.devDependencies | .[]')
            do
              json=$(echo $json | jq --arg version "$version" --arg name "$name" '.devDependencies += {($name): "^" + $version}')
            done
            echo $json > $package
          done
          echo "value=$staging" >> $GITHUB_OUTPUT
          echo "modules=$names" >> $GITHUB_OUTPUT
      - name: commit version
        if: ${{ steps.staging.outputs.value != '' }}
        uses: pmeig/github-actions/actions/github/push@main
        with:
          commit: "semver(${{ steps.type.outputs.value }}): bump version for ${{ steps.staging.outputs.modules }}"
          stage: ${{ steps.staging.outputs.value }}
          mail: 'pierrick.workplace@gmail.com'
          user: 'pmeig'